backend:
  name: github
  repo: tvoiat-potrebitel/tvoiat-proekt # Заменете с вашето име/репозитори
  branch: main # Или master

media_folder: "public/images" # Къде ще се записват новите снимки
public_folder: "/images"

collections:
  - name: "products"
    label: "Продукти"
    folder: "content/products" # Къде се съхраняват данните (напр. в JSON или Markdown)
    create: true
    fields:
      - { label: "Име на продукта", name: "title", widget: "string" }
      - { label: "Цена", name: "price", widget: "number", value_type: "float" }
      - { label: "Снимка", name: "image", widget: "image" }
      - { label: "Описание", name: "body", widget: "markdown" }
