backend:
  name: github
  repo: SergeyAld/rahoff-hotel
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "gallery" # Използваме твоята съществуваща папка
public_folder: "gallery"

collections:
  - name: "data"
    label: "Данни за сайта"
    files:
      - name: "prices"
        label: "Цени на стаи"
        file: "prices.json" # CMS-ът ще създаде и редактира този файл
        fields:
          - label: "Списък със стаи"
            name: "rooms"
            widget: "list"
            fields:
              - { label: "Име на стаята", name: "name", widget: "string" }
              - { label: "Цена", name: "price", widget: "string" }
              - { label: "Снимка", name: "image", widget: "image" }
